name: Testing this new flow

on:
  push:
    branches:
      - main

jobs:
  release-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.TOKEN_2 }}
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Semantic release
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_2 }}
          NPM_TOKEN: ${{ secrets.TOKEN_2 }}
          NODE_AUTH_TOKEN: ${{ secrets.TOKEN_2 }}
          HUSKY: 0
          CI: true
        run: |
          export HUSKY=0
          export CI=true
          npx semantic-release
